Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  Max: 80

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  Description: 'Check if exceptions are raised in a particular way'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/MethodLength:
  Description: Avoid methods longer than 25 lines of code.
  Enabled: true
  CountComments: false
  Max: 25

Style/ClassAndModuleChildren:
  Description: Checks style of children classes and modules.
  Enabled: false
  EnforcedStyle: nested

Style/AlignParameters:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Style/NumericLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false

